name: Node CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install --global windows-build-tools
      run: |
        npm install --global  --production windows-build-tools@4.0.0 --vs2015
      continue-on-error: true
    - name: npm install && npm test
      run: |
        cd camera-capture
        npm install
        npm test
      env:
        CI: true
